# Generated by Django 4.2.22 on 2025-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_verified_user_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_logout",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
