# Generated by Django 5.0.7 on 2025-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_logout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_logout",
            field=models.DateTimeField(
                blank=True, help_text="Last logout timestamp", null=True
            ),
        ),
    ]
