# Generated by Django 4.2.22 on 2025-08-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_last_logout"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When the user was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who archived this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="User PII has been anonymized"
            ),
        ),
    ]
