# Generated by Django 4.2.22 on 2025-06-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_a_id", models.CharField(max_length=32)),
                ("student_b_id", models.CharField(max_length=32)),
                (
                    "similarity_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("flagged", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_checks",
                        to="exams.variant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoreDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mean", models.DecimalField(decimal_places=2, max_digits=5)),
                ("median", models.DecimalField(decimal_places=2, max_digits=5)),
                ("std_dev", models.DecimalField(decimal_places=2, max_digits=5)),
                ("histogram_json", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_distributions",
                        to="exams.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                ("incorrect_attempts", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
