# Generated by Django 4.2.22 on 2025-08-05 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_courseactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0020_add_exam_template"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarityFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Similarity percentage between 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("confirmed", "Confirmed Violation"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "flagged_questions",
                    models.JSONField(
                        default=list,
                        help_text="List of question numbers with identical answers",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Review notes or comments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_flags",
                        to="exams.exam",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_similarity_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_flags_as_student1",
                        to="courses.student",
                    ),
                ),
                (
                    "student2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_flags_as_student2",
                        to="courses.student",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_score", "-created_at"],
                "unique_together": {("exam", "student1", "student2")},
            },
        ),
    ]
