# Generated by Django 5.0.7 on 2025-07-22 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique setting identifier", max_length=100
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("marking-scheme", "Marking Scheme"),
                            ("exam-format", "Exam Format"),
                            ("system-config", "System Configuration"),
                            ("ui-config", "UI Configuration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable setting name", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Setting description"),
                ),
                (
                    "value",
                    models.JSONField(
                        default=dict, help_text="Setting configuration as JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the default configuration for this type?",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Setting",
                "verbose_name_plural": "Global Settings",
                "ordering": ["setting_type", "name"],
                "unique_together": {("key", "setting_type")},
            },
        ),
        migrations.CreateModel(
            name="ExamFormat",
            fields=[
                (
                    "global_setting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="examvault.globalsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkingScheme",
            fields=[
                (
                    "global_setting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="examvault.globalsetting",
                    ),
                ),
            ],
        ),
    ]
