# Generated by Django 4.2.22 on 2025-08-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examvault", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_archived", "User Archived"),
                            ("user_deleted", "User Deleted"),
                            ("data_exported", "Data Exported"),
                            ("user_anonymized", "User Anonymized"),
                            ("user_search", "User Search"),
                            ("data_access", "Data Access"),
                            ("privacy_settings_changed", "Privacy Settings Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "admin_user",
                    models.CharField(
                        help_text="Admin who performed the action", max_length=100
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        blank=True,
                        help_text="Email of affected user (if applicable)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Privacy Audit Log",
                "verbose_name_plural": "Privacy Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
