# Generated by Django 4.2.22 on 2025-06-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("results", "0002_delete_studentresponse"),
        ("exams", "0003_remove_questionbank_course_delete_question_and_more"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="exams.course",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="exam",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answers",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.AddField(
            model_name="question",
            name="question_bank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.questionbank",
            ),
        ),
    ]
