# Generated by Django 4.2.22 on 2025-06-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_copy_course_data"),
        ("questions", "0002_questionbank_remove_question_exam_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["bank", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="questionbank",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="prompt",
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_answers",
        ),
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_bank",
        ),
        migrations.AddField(
            model_name="question",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.questionbank",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="choices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Explanation shown after answering"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
