# Generated by Django 4.2.22 on 2025-07-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_recreate_question_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                blank=True, choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")], null=True
            ),
        ),
    ]
