# Generated by Django 4.2.22 on 2025-08-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_allow_null_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="incorrect_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Penalty for incorrect selections in partial credit (0-1)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="partial_credit_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether partial credit is allowed for multi-answer questions",
            ),
        ),
    ]
