# Generated by Django 4.2.22 on 2025-08-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_question_incorrect_penalty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="partial_credit_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether partial credit is allowed for multi-answer questions",
            ),
        ),
    ]
