# Generated by Django 4.2.22 on 2025-06-16 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("term", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="exam",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="description",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="label",
        ),
        migrations.AddField(
            model_name="exam",
            name="num_variants",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="variant",
            name="version_label",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="exams.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("options", models.JSONField()),
                ("correct_answers", models.JSONField()),
                ("difficulty", models.IntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.questionbank",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam",
                to="exams.course",
            ),
        ),
    ]
