# Generated by Django 4.2.22 on 2025-06-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_course_remove_exam_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionbank",
            name="course",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="QuestionBank",
        ),
    ]
