# Generated by Django 4.2.22 on 2025-06-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_copy_course_data"),
        ("exams", "0003_remove_questionbank_course_delete_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override default question points for this exam",
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="variant",
            options={"ordering": ["version_label"]},
        ),
        migrations.RemoveField(
            model_name="exam",
            name="num_variants",
        ),
        migrations.AddField(
            model_name="exam",
            name="attempts_allowed",
            field=models.IntegerField(
                default=1, help_text="Number of attempts allowed, 0 for unlimited"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="available_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="available_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz"),
                    ("midterm", "Midterm"),
                    ("final", "Final Exam"),
                    ("practice", "Practice Test"),
                ],
                default="quiz",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="randomize_choices",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="randomize_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="show_answers_after",
            field=models.BooleanField(
                default=True, help_text="Show correct answers after submission"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="time_limit",
            field=models.IntegerField(
                default=0, help_text="Time limit in minutes, 0 for unlimited"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="variant",
            name="version_label",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="variant",
            unique_together={("exam", "version_label")},
        ),
    ]
