# Generated by Django 4.2.22 on 2025-06-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0003_alter_question_options_alter_questionbank_options_and_more",
        ),
        ("exams", "0004_examquestion_remove_course_user_alter_exam_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.question"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                related_name="exams",
                through="exams.ExamQuestion",
                to="questions.question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examquestion",
            unique_together={("exam", "question")},
        ),
    ]
