# Generated by Django 4.2.22 on 2025-06-28 23:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0003_alter_question_options_alter_questionbank_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0005_delete_course_examquestion_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="easy_percentage",
            field=models.IntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="hard_percentage",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="mandatory_questions",
            field=models.ManyToManyField(
                blank=True, related_name="mandatory_in_exams", to="questions.question"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="medium_percentage",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="num_variants",
            field=models.IntegerField(
                default=1,
                help_text="Number of variants to generate",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(26),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="question_budget",
            field=models.IntegerField(
                default=200, help_text="Total question pool size to draw from"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="questions_per_variant",
            field=models.IntegerField(
                default=20,
                help_text="Number of questions per variant",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="docx_exported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="variant",
            name="exported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="pdf_exported",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="variant",
            name="version_label",
            field=models.CharField(
                default="A",
                help_text='Version label for the variant (e.g. "A", "B", "C")',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="VariantQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.variant"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("variant", "question")},
            },
        ),
        migrations.CreateModel(
            name="ExamExportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX"), ("both", "Both")],
                        max_length=10,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_history",
                        to="exams.exam",
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("variants_exported", models.ManyToManyField(to="exams.variant")),
            ],
            options={
                "ordering": ["-exported_at"],
            },
        ),
        migrations.AddField(
            model_name="variant",
            name="questions",
            field=models.ManyToManyField(
                related_name="in_variants",
                through="exams.VariantQuestion",
                to="questions.question",
            ),
        ),
    ]
