# Generated by Django 4.2.22 on 2025-07-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_easy_percentage_exam_hard_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="attempts_allowed",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="is_published",
        ),
        migrations.AddField(
            model_name="exam",
            name="required_to_pass",
            field=models.BooleanField(
                default=False, help_text="Is this exam required to pass the course?"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of course grade this exam counts for",
                max_digits=5,
            ),
        ),
    ]
