# Generated by Django 4.2.22 on 2025-07-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_remove_exam_attempts_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked variants cannot be edited"
            ),
        ),
    ]
