# Generated by Django 4.2.22 on 2025-07-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_add_is_locked_to_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="allow_reuse",
            field=models.BooleanField(
                default=False, help_text="Allow question reuse between variants"
            ),
        ),
    ]
