# Generated by Django 4.2.22 on 2025-07-08 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0009_add_allow_reuse_to_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StudentVariantAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seat_number",
                    models.CharField(
                        blank=True,
                        help_text="Physical seat number for exam administration",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "row_number",
                    models.CharField(
                        blank=True,
                        help_text="Row number for seating arrangement",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Administrative notes"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_assignments",
                        to="courses.student",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="exams.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["assigned_at"],
                "unique_together": {("student", "exam")},
            },
        ),
    ]
