# Generated by Django 4.2.22 on 2025-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_add_student_variant_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantquestion",
            name="randomized_choices",
            field=models.JSONField(
                blank=True, help_text="Randomized choices for this variant", null=True
            ),
        ),
        migrations.AddField(
            model_name="variantquestion",
            name="randomized_correct_answer",
            field=models.JSONField(
                blank=True,
                help_text="Randomized correct answer for this variant",
                null=True,
            ),
        ),
    ]
