# Generated by Django 4.2.22 on 2025-07-10 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_variantquestion_randomized_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="time_limit",
            field=models.IntegerField(
                default=0,
                help_text="Time limit in minutes, 0 for unlimited",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of course grade this exam counts for",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
