# Generated by Django 4.2.22 on 2025-07-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0012_alter_exam_time_limit_alter_exam_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
