# Generated by Django 4.2.22 on 2025-07-20 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0013_exam_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="unknown_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Percentage of questions with unknown difficulty.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
