# Generated by Django 4.2.22 on 2025-07-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0014_exam_unknown_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examexporthistory",
            name="export_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("docx", "DOCX"), ("both", "Both")],
                max_length=20,
            ),
        ),
    ]
