# Generated by Django 4.2.22 on 2025-07-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_allow_null_difficulty"),
        ("exams", "0015_alter_examexporthistory_export_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="academic_integrity_statement",
            field=models.TextField(
                blank=True, help_text="Custom academic integrity statement"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_instructions",
            field=models.TextField(
                blank=True, help_text="Instructions shown at the top of the exam"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="footer_text",
            field=models.CharField(
                blank=True,
                help_text="Footer text for the exam document",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="include_academic_integrity",
            field=models.BooleanField(
                default=True, help_text="Include academic integrity statement in exam"
            ),
        ),
        migrations.CreateModel(
            name="ExamSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instructions specific to this section"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of this section in the exam"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="exams.exam",
                    ),
                ),
                (
                    "question_banks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Question banks used in this section",
                        related_name="exam_sections",
                        to="questions.questionbank",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "unique_together": {("exam", "title")},
            },
        ),
    ]
