# Generated by Django 4.2.22 on 2025-07-27 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0016_exam_academic_integrity_statement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsection",
            name="configured_question_count",
            field=models.IntegerField(
                default=5,
                help_text="Number of questions to select from this section during variant generation",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
