# Generated by Django 4.2.22 on 2025-07-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0017_examsection_configured_question_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantquestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section this question belongs to in this variant",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.examsection",
            ),
        ),
    ]
