# Generated by Django 4.2.22 on 2025-07-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0018_add_section_to_variantquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="randomize_choices",
            field=models.BooleanField(default=True),
        ),
    ]
