# Generated by Django 4.2.22 on 2025-08-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0020_add_exam_template"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variant",
            unique_together=set(),
        ),
    ]
