# Generated by Django 4.2.22 on 2025-08-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0022_add_marking_scheme_to_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="marking_scheme",
        ),
    ]
