# Generated by Django 4.2.22 on 2025-08-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0023_remove_exam_marking_scheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="marking_scheme",
            field=models.JSONField(
                default=dict, help_text="Marking scheme configuration for this exam"
            ),
        ),
    ]
