# Generated by Django 4.2.22 on 2025-08-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0024_exam_marking_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantquestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section this question belongs to in this variant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exams.examsection",
            ),
        ),
    ]
