# Generated by Django 4.2.22 on 2025-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0025_alter_variantquestion_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this template is the default for all users",
            ),
        ),
        migrations.AddConstraint(
            model_name="examtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="only_one_default_template",
            ),
        ),
    ]
