# Generated by Django 4.2.22 on 2025-06-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_copy_course_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="last_edited",
            field=models.DateTimeField(
                auto_now=True, help_text="Automatically updated to now() on every save"
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("student_id", models.CharField(max_length=50, unique=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("course", "student_id")},
            },
        ),
    ]
