# Generated by Django 4.2.22 on 2025-06-30 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_alter_course_last_edited_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="anonymous_id",
            field=models.CharField(
                blank=True,
                help_text="Anonymized identifier for privacy-compliant analysis",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="dropped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="If True, student data is anonymized for analysis",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Instructor notes about the student"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(
                blank=True, help_text="Course section (e.g., 'A', 'B')", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
