# Generated by Django 4.2.22 on 2025-06-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_student_anonymous_id_student_dropped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, help_text="Course description"),
        ),
    ]
