# Generated by Django 4.2.22 on 2025-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_created_at_course_instructor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=50),
        ),
    ]
