# Generated by Django 4.2.22 on 2025-07-20 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0007_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="User who originally created the course",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.CharField(
                blank=True,
                help_text="Optional display name for the main instructor if different from creator.name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="anonymous_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MAIN", "Main Instructor"),
                            ("SEC", "Secondary Instructor"),
                            ("TA", "Teaching Assistant"),
                            ("OTH", "Other Instructor"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Access"),
                            ("LIMITED", "Limited Access (View Only)"),
                            ("NONE", "No Access"),
                        ],
                        default="FULL",
                        max_length=7,
                    ),
                ),
                ("invited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_instructors",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "user__name"],
                "unique_together": {("course", "user")},
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="instructors",
        ),
        # 2) add the new M2M that points at the through‑model
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                through="courses.CourseInstructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
