# Generated by Django 4.2.22 on 2025-07-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_creator_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="default_oth_access",
            field=models.CharField(
                choices=[("FULL", "Full"), ("LIMITED", "Limited"), ("NONE", "None")],
                default="NONE",
                help_text="Default access for newly invited Other‑role instructors",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="default_sec_access",
            field=models.CharField(
                choices=[("FULL", "Full"), ("LIMITED", "Limited"), ("NONE", "None")],
                default="LIMITED",
                help_text="Default access for newly invited Secondary Instructors",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="default_ta_access",
            field=models.CharField(
                choices=[("FULL", "Full"), ("LIMITED", "Limited"), ("NONE", "None")],
                default="LIMITED",
                help_text="Default access for newly invited TAs",
                max_length=7,
            ),
        ),
    ]
