# Generated by Django 4.2.22 on 2025-07-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_courseexporthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseexporthistory",
            name="export_format",
            field=models.CharField(default="zip", max_length=10),
        ),
        migrations.AddField(
            model_name="courseexporthistory",
            name="file_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
