# Generated by Django 4.2.22 on 2025-07-31 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_courseexporthistory_export_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="Course code (max 10 characters)",
                max_length=20,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        10, message="Course code must be 10 characters or less"
                    )
                ],
            ),
        ),
    ]
