# Generated by Django 4.2.22 on 2025-08-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="Student's preferred name (optional)",
                max_length=255,
                null=True,
            ),
        ),
    ]
