# Generated by Django 4.2.22 on 2025-08-03 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0013_student_preferred_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("course_created", "Course Created"),
                            ("course_updated", "Course Updated"),
                            ("exam_created", "Exam Created"),
                            ("exam_updated", "Exam Updated"),
                            ("exam_deleted", "Exam Deleted"),
                            ("exam_exported", "Exam Exported"),
                            ("variants_generated", "Variants Generated"),
                            ("questions_added", "Questions Added to Exam"),
                            ("questions_removed", "Questions Removed from Exam"),
                            ("student_added", "Student Added"),
                            ("student_removed", "Student Removed"),
                            ("instructor_added", "Instructor Added"),
                            ("instructor_removed", "Instructor Removed"),
                            ("results_imported", "Results Imported"),
                            ("question_bank_added", "Question Bank Added"),
                            ("question_bank_removed", "Question Bank Removed"),
                            ("section_updated", "Exam Section Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("entity_type", models.CharField(max_length=50, null=True)),
                ("entity_id", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["course", "-created_at"],
                        name="courses_cou_course__aaa54b_idx",
                    )
                ],
            },
        ),
    ]
