import '@testing-library/jest-dom/vitest';
import { server } from './msw/server';
import React from 'react';
import { cleanup } from '@testing-library/react';

// Cleanup after each test
afterEach(() => {
  cleanup();
});

vi.mock('@mui/x-data-grid', () => ({
  DataGrid: () => null,
  GridColDef: {},
  GridRowsProp: {},
}));

// Mock lucide-react icons
vi.mock('lucide-react', () => {
  const mockIcon = (name: string) => {
    const MockedIcon = (props: any) => {
      return React.createElement(
        'div',
        {
          'data-testid': `${name.toLowerCase()}-icon`,
          className: props.className,
          ...props,
        },
        `${name}Icon`
      );
    };
    MockedIcon.displayName = name;
    return MockedIcon;
  };

  return {
    BookOpen: mockIcon('BookOpen'),
    Users: mockIcon('Users'),
    FileText: mockIcon('FileText'),
    TrendingUp: mockIcon('TrendingUp'),
    BarChart3: mockIcon('BarChart3'),
    BarChart2: mockIcon('BarChart2'),
    PieChart: mockIcon('PieChart'),
    Calendar: mockIcon('Calendar'),
    Clock: mockIcon('Clock'),
    CheckCircle: mockIcon('CheckCircle'),
    CheckCircle2: mockIcon('CheckCircle2'),
    AlertTriangle: mockIcon('AlertTriangle'),
    Info: mockIcon('Info'),
    Star: mockIcon('Star'),
    Award: mockIcon('Award'),
    Target: mockIcon('Target'),
    ArrowUp: mockIcon('ArrowUp'),
    ArrowDown: mockIcon('ArrowDown'),
    ArrowRight: mockIcon('ArrowRight'),
    ArrowLeft: mockIcon('ArrowLeft'),
    Plus: mockIcon('Plus'),
    Minus: mockIcon('Minus'),
    X: mockIcon('X'),
    Check: mockIcon('Check'),
    Search: mockIcon('Search'),
    Filter: mockIcon('Filter'),
    Download: mockIcon('Download'),
    Upload: mockIcon('Upload'),
    Settings: mockIcon('Settings'),
    MoreHorizontal: mockIcon('MoreHorizontal'),
    MoreVertical: mockIcon('MoreVertical'),
    ChevronUp: mockIcon('ChevronUp'),
    ChevronDown: mockIcon('ChevronDown'),
    ChevronLeft: mockIcon('ChevronLeft'),
    ChevronRight: mockIcon('ChevronRight'),
    Eye: mockIcon('Eye'),
    EyeOff: mockIcon('EyeOff'),
    Edit: mockIcon('Edit'),
    Edit3: mockIcon('Edit3'),
    Trash: mockIcon('Trash'),
    Trash2: mockIcon('Trash2'),
    Copy: mockIcon('Copy'),
    Share: mockIcon('Share'),
    ExternalLink: mockIcon('ExternalLink'),
    Pin: mockIcon('Pin'),
    Book: mockIcon('Book'),
    Trophy: mockIcon('Trophy'),
    Activity: mockIcon('Activity'),
    RefreshCw: mockIcon('RefreshCw'),
    GitCompare: mockIcon('GitCompare'),
    Flag: mockIcon('Flag'),
    // Add more icons that might be missing
    User: mockIcon('User'),
    Home: mockIcon('Home'),
    BarChart: mockIcon('BarChart'),
    Heart: mockIcon('Heart'),
    ThumbsUp: mockIcon('ThumbsUp'),
    ThumbsDown: mockIcon('ThumbsDown'),
    Bell: mockIcon('Bell'),
    Mail: mockIcon('Mail'),
    Folder: mockIcon('Folder'),
    File: mockIcon('File'),
    Image: mockIcon('Image'),
    Camera: mockIcon('Camera'),
    Mic: mockIcon('Mic'),
    Play: mockIcon('Play'),
    Pause: mockIcon('Pause'),
    Stop: mockIcon('Stop'),
    Volume: mockIcon('Volume'),
    VolumeX: mockIcon('VolumeX'),
    Wifi: mockIcon('Wifi'),
    Battery: mockIcon('Battery'),
    Power: mockIcon('Power'),
    Shield: mockIcon('Shield'),
    Lock: mockIcon('Lock'),
    Unlock: mockIcon('Unlock'),
    Key: mockIcon('Key'),
    XCircle: mockIcon('XCircle'),
    HelpCircle: mockIcon('HelpCircle'),
    Menu: mockIcon('Menu'),
    Grid: mockIcon('Grid'),
    List: mockIcon('List'),
    Sliders: mockIcon('Sliders'),
    Tag: mockIcon('Tag'),
    Hash: mockIcon('Hash'),
    Percent: mockIcon('Percent'),
    Type: mockIcon('Type'),
    Zap: mockIcon('Zap'),
    RotateCcw: mockIcon('RotateCcw'),
    RotateCw: mockIcon('RotateCw'),
    Save: mockIcon('Save'),
    Clipboard: mockIcon('Clipboard'),
    Database: mockIcon('Database'),
    Server: mockIcon('Server'),
    Monitor: mockIcon('Monitor'),
    Smartphone: mockIcon('Smartphone'),
    Tablet: mockIcon('Tablet'),
    Laptop: mockIcon('Laptop'),
    Printer: mockIcon('Printer'),
    Headphones: mockIcon('Headphones'),
    Speaker: mockIcon('Speaker'),
    Bluetooth: mockIcon('Bluetooth'),
    Cpu: mockIcon('Cpu'),
    HardDrive: mockIcon('HardDrive'),
    MemoryStick: mockIcon('MemoryStick'),
    Link: mockIcon('Link'),
    Maximize: mockIcon('Maximize'),
    Minimize: mockIcon('Minimize'),
    ZoomIn: mockIcon('ZoomIn'),
    ZoomOut: mockIcon('ZoomOut'),
    MessageCircle: mockIcon('MessageCircle'),
    MessageSquare: mockIcon('MessageSquare'),
    Send: mockIcon('Send'),
    BellOff: mockIcon('BellOff'),
    WifiOff: mockIcon('WifiOff'),
    FileDown: mockIcon('FileDown'),
  };
});

// Mock react-icons completely to avoid import issues in tests
vi.mock('react-icons/fi', () => {
  const mockIcon = (name: string) => {
    const MockedIcon = (props: any) => {
      return React.createElement(
        'div',
        {
          'data-testid': `icon-${name.toLowerCase()}`,
          className: props.className,
          ...props,
        },
        name
      );
    };
    MockedIcon.displayName = name;
    return MockedIcon;
  };

  return {
    default: {},
    FiEye: mockIcon('FiEye'),
    FiEdit: mockIcon('FiEdit'),
    FiEdit2: mockIcon('FiEdit2'),
    FiTrash: mockIcon('FiTrash'),
    FiTrash2: mockIcon('FiTrash2'),
    FiPlus: mockIcon('FiPlus'),
    FiRefreshCw: mockIcon('FiRefreshCw'),
    FiSearch: mockIcon('FiSearch'),
    FiSettings: mockIcon('FiSettings'),
    FiUser: mockIcon('FiUser'),
    FiUsers: mockIcon('FiUsers'),
    FiBook: mockIcon('FiBook'),
    FiFileText: mockIcon('FiFileText'),
    FiBarChart: mockIcon('FiBarChart'),
    FiBarChart2: mockIcon('FiBarChart2'),
    FiChevronDown: mockIcon('FiChevronDown'),
    FiChevronUp: mockIcon('FiChevronUp'),
    FiFilter: mockIcon('FiFilter'),
    FiCheckCircle: mockIcon('FiCheckCircle'),
    FiHome: mockIcon('FiHome'),
    FiCalendar: mockIcon('FiCalendar'),
    FiClock: mockIcon('FiClock'),
    FiTrendingUp: mockIcon('FiTrendingUp'),
    FiTarget: mockIcon('FiTarget'),
    FiActivity: mockIcon('FiActivity'),
    FiAward: mockIcon('FiAward'),
    FiAlertTriangle: mockIcon('FiAlertTriangle'),
    FiDownload: mockIcon('FiDownload'),
    FiUpload: mockIcon('FiUpload'),
    FiExternalLink: mockIcon('FiExternalLink'),
    FiMail: mockIcon('FiMail'),
    FiPhone: mockIcon('FiPhone'),
    FiMapPin: mockIcon('FiMapPin'),
    FiLogOut: mockIcon('FiLogOut'),
    FiGrid: mockIcon('FiGrid'),
    FiList: mockIcon('FiList'),
    FiSliders: mockIcon('FiSliders'),
    FiTag: mockIcon('FiTag'),
    FiHash: mockIcon('FiHash'),
    FiPercent: mockIcon('FiPercent'),
    FiType: mockIcon('FiType'),
    FiImage: mockIcon('FiImage'),
    FiVideo: mockIcon('FiVideo'),
    FiMusic: mockIcon('FiMusic'),
    FiFile: mockIcon('FiFile'),
    FiFolder: mockIcon('FiFolder'),
    FiArchive: mockIcon('FiArchive'),
    FiSave: mockIcon('FiSave'),
    FiCopy: mockIcon('FiCopy'),
    FiScissors: mockIcon('FiScissors'),
    FiClipboard: mockIcon('FiClipboard'),
    FiDatabase: mockIcon('FiDatabase'),
    FiServer: mockIcon('FiServer'),
    FiMonitor: mockIcon('FiMonitor'),
    FiSmartphone: mockIcon('FiSmartphone'),
    FiTablet: mockIcon('FiTablet'),
    FiLaptop: mockIcon('FiLaptop'),
    FiPrinter: mockIcon('FiPrinter'),
    FiCamera: mockIcon('FiCamera'),
    FiMic: mockIcon('FiMic'),
    FiHeadphones: mockIcon('FiHeadphones'),
    FiSpeaker: mockIcon('FiSpeaker'),
    FiVolume: mockIcon('FiVolume'),
    FiVolumeX: mockIcon('FiVolumeX'),
    FiPlay: mockIcon('FiPlay'),
    FiPause: mockIcon('FiPause'),
    FiSkipBack: mockIcon('FiSkipBack'),
    FiSkipForward: mockIcon('FiSkipForward'),
    FiRewind: mockIcon('FiRewind'),
    FiFastForward: mockIcon('FiFastForward'),
    // Missing icons that are causing test failures
    FiX: mockIcon('FiX'),
    FiCheck: mockIcon('FiCheck'),
    FiLock: mockIcon('FiLock'),
    FiUnlock: mockIcon('FiUnlock'),
    FiInfo: mockIcon('FiInfo'),
    FiHelpCircle: mockIcon('FiHelpCircle'),
    FiMoreHorizontal: mockIcon('FiMoreHorizontal'),
    FiMoreVertical: mockIcon('FiMoreVertical'),
    FiArrowUp: mockIcon('FiArrowUp'),
    FiArrowDown: mockIcon('FiArrowDown'),
    FiArrowLeft: mockIcon('FiArrowLeft'),
    FiArrowRight: mockIcon('FiArrowRight'),
    FiMinimize: mockIcon('FiMinimize'),
    FiMaximize: mockIcon('FiMaximize'),
    FiZoomIn: mockIcon('FiZoomIn'),
    FiZoomOut: mockIcon('FiZoomOut'),
    FiRotateCcw: mockIcon('FiRotateCcw'),
    FiRotateCw: mockIcon('FiRotateCw'),
    FiShare: mockIcon('FiShare'),
    FiShare2: mockIcon('FiShare2'),
    FiStar: mockIcon('FiStar'),
    FiHeart: mockIcon('FiHeart'),
    FiThumbsUp: mockIcon('FiThumbsUp'),
    FiThumbsDown: mockIcon('FiThumbsDown'),
    FiMessageCircle: mockIcon('FiMessageCircle'),
    FiMessageSquare: mockIcon('FiMessageSquare'),
    FiSend: mockIcon('FiSend'),
    FiBell: mockIcon('FiBell'),
    FiBellOff: mockIcon('FiBellOff'),
    FiWifi: mockIcon('FiWifi'),
    FiWifiOff: mockIcon('FiWifiOff'),
    FiBluetooth: mockIcon('FiBluetooth'),
    FiBattery: mockIcon('FiBattery'),
    FiPower: mockIcon('FiPower'),
    FiCpu: mockIcon('FiCpu'),
    FiHardDrive: mockIcon('FiHardDrive'),
    FiMemory: mockIcon('FiMemory'),
  };
});

vi.mock('react-icons/fa', () => ({
  FaUser: () => null,
  FaBook: () => null,
  FaChart: () => null,
  FaGraduationCap: () => null,
  FaClipboardList: () => null,
  FaCog: () => null,
  FaSignOutAlt: () => null,
  FaHome: () => null,
  FaUsers: () => null,
  FaFileAlt: () => null,
  FaChartBar: () => null,
  FaDatabase: () => null,
  FaBell: () => null,
  FaEnvelope: () => null,
  FaCalendar: () => null,
  FaClock: () => null,
  FaTrophy: () => null,
  FaMedal: () => null,
  FaStar: () => null,
  FaHeart: () => null,
  FaThumbsUp: () => null,
  FaEye: () => null,
  FaEdit: () => null,
  FaTrash: () => null,
  FaPlus: () => null,
  FaMinus: () => null,
  FaSearch: () => null,
  FaFilter: () => null,
  FaSort: () => null,
  FaDownload: () => null,
  FaUpload: () => null,
  FaPrint: () => null,
  FaShare: () => null,
  FaLink: () => null,
  FaExternalLinkAlt: () => null,
  FaArrowUp: () => null,
  FaArrowDown: () => null,
  FaArrowLeft: () => null,
  FaArrowRight: () => null,
  FaChevronUp: () => null,
  FaChevronDown: () => null,
  FaChevronLeft: () => null,
  FaChevronRight: () => null,
  FaTimes: () => null,
  FaCheck: () => null,
  FaExclamationTriangle: () => null,
  FaInfoCircle: () => null,
  FaQuestionCircle: () => null,
  FaSpinner: () => null,
  FaLock: () => null,
  FaUnlock: () => null,
  FaKey: () => null,
  FaShield: () => null,
  FaUserShield: () => null,
  FaCheckCircle: () => null,
  FaTimesCircle: () => null,
  FaPlayCircle: () => null,
  FaPauseCircle: () => null,
  FaStopCircle: () => null,
  FaSync: () => null,
  FaRedo: () => null,
  FaUndo: () => null,
  FaSave: () => null,
  FaCopy: () => null,
  FaCut: () => null,
  FaPaste: () => null,
  FaClipboard: () => null,
  FaFolder: () => null,
  FaFolderOpen: () => null,
  FaFile: () => null,
  FaFileText: () => null,
  FaFileImage: () => null,
  FaFilePdf: () => null,
  FaFileWord: () => null,
  FaFileExcel: () => null,
  FaFilePowerpoint: () => null,
  FaFileArchive: () => null,
  FaFileCode: () => null,
  FaImage: () => null,
  FaVideo: () => null,
  FaMusic: () => null,
  FaVolumeUp: () => null,
  FaVolumeDown: () => null,
  FaVolumeMute: () => null,
  FaPlay: () => null,
  FaPause: () => null,
  FaStop: () => null,
  FaStepForward: () => null,
  FaStepBackward: () => null,
  FaFastForward: () => null,
  FaFastBackward: () => null,
  FaRandom: () => null,
  FaRepeat: () => null,
}));

vi.mock('react-icons/bs', () => ({
  BsThreeDotsVertical: () => null,
  BsCheck: () => null,
  BsX: () => null,
  BsPlus: () => null,
  BsMinus: () => null,
  BsEye: () => null,
  BsEyeSlash: () => null,
  BsPencil: () => null,
  BsTrash: () => null,
  BsSearch: () => null,
  BsFilter: () => null,
  BsSort: () => null,
  BsArrowUp: () => null,
  BsArrowDown: () => null,
  BsArrowLeft: () => null,
  BsArrowRight: () => null,
  BsChevronUp: () => null,
  BsChevronDown: () => null,
  BsChevronLeft: () => null,
  BsChevronRight: () => null,
  BsDownload: () => null,
  BsUpload: () => null,
  BsShare: () => null,
  BsHeart: () => null,
  BsStar: () => null,
  BsBookmark: () => null,
  BsGear: () => null,
  BsBell: () => null,
  BsEnvelope: () => null,
  BsCalendar: () => null,
  BsClock: () => null,
  BsFolder: () => null,
  BsFile: () => null,
  BsImage: () => null,
  BsCamera: () => null,
  BsMic: () => null,
  BsPlay: () => null,
  BsPause: () => null,
  BsStop: () => null,
  BsVolume: () => null,
  BsVolumeOff: () => null,
  BsWifi: () => null,
  BsBattery: () => null,
  BsPower: () => null,
  BsShield: () => null,
  BsLock: () => null,
  BsUnlock: () => null,
  BsKey: () => null,
  BsCheckCircle: () => null,
  BsXCircle: () => null,
  BsInfoCircle: () => null,
  BsExclamationTriangle: () => null,
  BsQuestionCircle: () => null,
}));

vi.mock('react-icons/ai', () => ({
  AiOutlineLoading3Quarters: () => null,
  AiOutlineCheck: () => null,
  AiOutlineClose: () => null,
  AiOutlineEye: () => null,
  AiOutlineEyeInvisible: () => null,
  AiOutlineEdit: () => null,
  AiOutlineDelete: () => null,
  AiOutlinePlus: () => null,
  AiOutlineMinus: () => null,
  AiOutlineSearch: () => null,
  AiOutlineFilter: () => null,
  AiOutlineSetting: () => null,
  AiOutlineUser: () => null,
  AiOutlineHome: () => null,
  AiOutlineBook: () => null,
  AiOutlineFileText: () => null,
  AiOutlineBarChart: () => null,
  AiOutlineDownload: () => null,
  AiOutlineUpload: () => null,
  AiOutlineShare: () => null,
  AiOutlineHeart: () => null,
  AiOutlineStar: () => null,
  AiOutlineLike: () => null,
  AiOutlineDislike: () => null,
  AiOutlineBell: () => null,
  AiOutlineMail: () => null,
  AiOutlineCalendar: () => null,
  AiOutlineClockCircle: () => null,
  AiOutlineFolder: () => null,
  AiOutlineFile: () => null,
  AiOutlinePicture: () => null,
  AiOutlineCamera: () => null,
  AiOutlineVideoCamera: () => null,
  AiOutlineAudio: () => null,
  AiOutlinePlayCircle: () => null,
  AiOutlinePauseCircle: () => null,
  AiOutlineSound: () => null,
  AiOutlineWifi: () => null,
  AiOutlineBattery: () => null,
  AiOutlinePoweroff: () => null,
  AiOutlineSafety: () => null,
  AiOutlineLock: () => null,
  AiOutlineUnlock: () => null,
  AiOutlineCheckCircle: () => null,
  AiOutlineCloseCircle: () => null,
  AiOutlineInfoCircle: () => null,
  AiOutlineWarning: () => null,
  AiOutlineQuestionCircle: () => null,
}));

/* MSW lifecycle hooks */
beforeAll(() => server.listen({ onUnhandledRequest: 'bypass' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
